### ISSUE TITLE
Cambios realizados

### ISSUE THREAD

**Issue by DamarisCamusett** [DamarisCamusett/Agencia-Viajes#2]
Si bien, se entiende que los colores corporativos son azules, sugeriría cambiar a un tono más Beige para que el color de las letras pueda visualizarse de mejor manera (Considero que se ven muy opaco).
![Captura de pantalla 2024-07-29 221118](https://github.com/user-attachments/assets/2960cf9f-b1fe-4859-bc05-f2ba118879ae)
Como considerando el color #f0f0f0 este se verá de la siguiente manera:
![Captura de pantalla 2024-07-29 221452](https://github.com/user-attachments/assets/f009f072-38fb-4900-b7b5-7da076132bd6)
Espero respuesta.

**Comment by DamarisCV** [comment]
He consultado y sí, es aceptable ese tono de color, permite además, diferenciar el titulo del formulario.

**Comment by DamarisCamusett** [comment]
Super, entonces aceptaremos el color propuesto, quedando en el código fuente.
