### ISSUE TITLE
Sistema Reservas

### ISSUE THREAD

**Issue by DamarisCamusett** [DamarisCamusett/Agencia-Viajes#4]
He diseñado el siguiente código HTML, para poder visualizar un nuevo sistema de reservas, pero, presentó fallas al procesar la reserva. 

![Captura de pantalla 2024-07-29 233948](https://github.com/user-attachments/assets/3472cfb0-82f0-4953-963e-d2f7c897d81b)

El código se encuentra en el siguiente archivo .txt:

[reserva-hotel.txt](https://github.com/user-attachments/files/16421698/reserva-hotel.txt)

**Comment by DamarisCV** [comment]
Me gusta el diseño del formulario.
Con respecto al fallo del código, creo que has olvidado subir el código de "POST".

**Comment by DamarisCamusett** [comment]
Ohh! Pido perdón, este es el código: 
[procesar-reserva.txt](https://github.com/user-attachments/files/16421731/procesar-reserva.txt)

**Comment by DamarisCV** [comment]
Revisando el código, veo que tienes problemas con la conexión a la base de datos.

**Comment by DamarisCamusett** [comment]
Lo revisaré de inmediato.

**Comment by DamarisCV** [comment]
Estaré atenta a si te ha funcionado, yo lo he corregido y si ha corrido el código.

**Comment by DamarisCamusett** [comment]
Muchas gracias por la corrección, ya he logrado solucionar el problema.
![Captura de pantalla 2024-07-30 001418](https://github.com/user-attachments/assets/f0a13b22-dbde-43da-b0ee-246ba6c264f2)

**Comment by DamarisCV** [comment]
Perfecto, entonces ya se podría revisar para implementarlo al código fuente.

**Comment by DamarisCamusett** [comment]
Si, exactamente.
